// models/medicalProfile.model.js
const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
    const MedicalProfile = sequelize.define('MedicalProfile', {
        surname: DataTypes.STRING,
        firstName: DataTypes.STRING,
        middleInitial: DataTypes.STRING,
        age: DataTypes.INTEGER,
        sex: DataTypes.STRING,
        dateOfBirth: DataTypes.DATEONLY,
        bloodType: DataTypes.STRING,
        gradeAndYear: DataTypes.STRING,
        familyPhysician: DataTypes.STRING,
        emergencyContactName: DataTypes.STRING,
        emergencyContactAddress: DataTypes.STRING,
        emergencyContactNumber: DataTypes.STRING,
        hasHighBloodPressure: DataTypes.BOOLEAN,
        hasAsthma: DataTypes.BOOLEAN,
        hasCancer: DataTypes.BOOLEAN,
        hasDiabetes: DataTypes.BOOLEAN,
        hasHeartDisease: DataTypes.BOOLEAN,
        hasEpilepsy: DataTypes.BOOLEAN,
        hasArthritis: DataTypes.BOOLEAN,
        hasTuberculosis: DataTypes.BOOLEAN,
        hadRecurrentNoseBleeding: DataTypes.BOOLEAN,
        hadEpilepsy: DataTypes.BOOLEAN,
        hadLossOfConsciousness: DataTypes.BOOLEAN,
        hadDizziness: DataTypes.BOOLEAN,
        hadHeadache: DataTypes.BOOLEAN,
        hadAsthma_self: DataTypes.BOOLEAN,
        hadSpittingOfBlood: DataTypes.BOOLEAN,
        hadChronicCough: DataTypes.BOOLEAN,
        hadPTB_LungDisease: DataTypes.BOOLEAN,
        hadHepatitis: DataTypes.BOOLEAN,
        hadHighBloodPressure_self: DataTypes.BOOLEAN,
        hadHeartDisease_self: DataTypes.BOOLEAN,
        hadChestPain: DataTypes.BOOLEAN,
        hadGastritisHyperacidity: DataTypes.BOOLEAN,
        hadAmoebiasis: DataTypes.BOOLEAN,
        hadUTI: DataTypes.BOOLEAN,
        hadKidneyDisease: DataTypes.BOOLEAN,
        hadAppendicitis: DataTypes.BOOLEAN,
        hadDiabetes_self: DataTypes.BOOLEAN,
        hadGoiter: DataTypes.BOOLEAN,
        hadArthritisBoneDisease: DataTypes.BOOLEAN,
        hadMentalDisorder: DataTypes.BOOLEAN,
        allergyToFoodDetails: DataTypes.STRING,
        allergyToMedicationDetails: DataTypes.STRING,
        recentStudiesCXR: DataTypes.TEXT,
        accidentInjuryMedicalAdvice: DataTypes.TEXT,
        previousHospitalAdmission: DataTypes.TEXT,
        isMarried: DataTypes.BOOLEAN,
        ageOfFirstMenstruation: DataTypes.INTEGER,
        dateOfLastMenstruation: DataTypes.DATEONLY,
        isMenstruationRegular: DataTypes.BOOLEAN,
        diseaseOfUterusOvaries: DataTypes.TEXT,
        isPregnant: DataTypes.BOOLEAN,
    });
    return MedicalProfile;
};
